export const images: [] = [
  {
      title: 'Hang in there',
      date: '10/09/2019',
      description: 'lorem ipsum blah blah',
      img: ('./Poster No. 6_Winner.jpg'),
      author: 'Tomás Rodríguez',
      categories: ['all, design'], // subject to change depending the links for the navbar
    },
    {
      title: 'Mt. Baldy',
      date: '10/10/2019',
      description: 'lorem ipsum blah blah',
      img:  ('./Poster No. 7_Winner.jpg'),
      author: 'Tomás Rodríguez',
      categories: ['all, design'],
    },
    {
      title: 'Sling and stone',
      date: '10/11/2019',
      description: 'lorem ipsum blah blah',
      img: ('./Poster No. 8_Winner.jpg'),
      author: 'Tomás Rodríguez',
      categories: ['all, design'],
    },
    {
      title: 'Autocorrect',
      date: '10/14/2019',
      description: 'lorem ipsum blah blah',
      img: ('./Poster No. 11_Winner.jpg'),
      author: 'Tomás Rodríguez',
      categories: ['all, design'],
    },
    {
      title: 'Permanent Beta',
      date: '10/21/2019',
      description: 'lorem ipsum blah blah',
      img: ('./Poster No. 18_Winner.jpg'),
      author: 'Tomás Rodríguez',
      categories: ['all, design'],
    },
    {
      title: 'Razer',
      date: '10/24/2019',
      description: 'lorem ipsum blah blah',
      img: ('./Poster No. 21_Bonus_Freebie Winner.jpg'),
      author: 'Tomás Rodríguez',
      categories: ['all, design'],
    },
    {
      title: 'Braun Hifi Audio System',
      date: '10/24/2019',
      description: 'lorem ipsum blah blah',
      img: ('./Braun Audio 300 by Dieter Rams.jpeg'),
      author: 'Dieter Rams',
      categories: ['all, other'],
    },
  ]
